import { JiraEpic, JiraStory } from './types';

/**
 * Parses the markdown generated by Claude and extracts structured epics + stories.
 *
 * Expected input sections:
 *   ## 2. Épicos sugeridos
 *   | EPIC-01 | Name | objective |
 *
 *   ## 3. Stories iniciais
 *   ### EPIC-01 — Name
 *   **US-001** — Como ...
 *   **Critérios de aceite**
 *   - criterion;
 */
export function parseBacklog(markdown: string): JiraEpic[] {
  const epicMap = new Map<string, JiraEpic>();

  // ── 1. Parse epic table ──────────────────────────────────────────────────
  // Matches: | EPIC-01 | Some Name | some objective |
  const tableRowRe = /\|\s*(EPIC-\d{2})\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/g;
  let m: RegExpExecArray | null;
  while ((m = tableRowRe.exec(markdown)) !== null) {
    const [, localKey, name, objective] = m;
    epicMap.set(localKey, { localKey, name: name.trim(), objective: objective.trim(), stories: [] });
  }

  // ── 2. Parse story blocks ─────────────────────────────────────────────────
  // Split on epic headings: ### EPIC-XX — Name
  const epicSectionRe = /###\s+(EPIC-\d{2})\s*[—–-]\s*([^\n]+)/g;
  const epicPositions: Array<{ key: string; name: string; start: number }> = [];

  while ((m = epicSectionRe.exec(markdown)) !== null) {
    epicPositions.push({ key: m[1], name: m[2].trim(), start: m.index });
  }

  epicPositions.forEach(({ key, name }, idx) => {
    const sectionStart = epicPositions[idx].start;
    const sectionEnd = idx + 1 < epicPositions.length ? epicPositions[idx + 1].start : markdown.length;
    const section = markdown.slice(sectionStart, sectionEnd);

    // Ensure epic exists even if it wasn't in the table
    if (!epicMap.has(key)) {
      epicMap.set(key, { localKey: key, name, objective: '', stories: [] });
    }

    const epic = epicMap.get(key)!;
    epic.stories.push(...parseStories(section));
  });

  return Array.from(epicMap.values()).filter((e) => e.stories.length > 0 || e.objective);
}

function parseStories(section: string): JiraStory[] {
  const stories: JiraStory[] = [];

  // Split on story headings: **US-001** — ...
  const storyRe = /\*\*(US-\d{3})\*\*\s*[—–-]\s*([^\n]+)/g;
  const storyPositions: Array<{ key: string; title: string; start: number }> = [];
  let m: RegExpExecArray | null;

  while ((m = storyRe.exec(section)) !== null) {
    storyPositions.push({ key: m[1], title: m[2].trim(), start: m.index });
  }

  storyPositions.forEach(({ key, title }, idx) => {
    const storyStart = storyPositions[idx].start;
    const storyEnd = idx + 1 < storyPositions.length ? storyPositions[idx + 1].start : section.length;
    const storyBlock = section.slice(storyStart, storyEnd);

    stories.push({ localKey: key, title, criteria: parseCriteria(storyBlock) });
  });

  return stories;
}

function parseCriteria(storyBlock: string): string[] {
  const criteriaHeaderRe = /\*\*Crit[eé]rios de aceite\*\*/i;
  const headerMatch = criteriaHeaderRe.exec(storyBlock);
  if (!headerMatch) return [];

  const afterHeader = storyBlock.slice(headerMatch.index + headerMatch[0].length);
  const criteria: string[] = [];

  // Collect bullet lines
  const bulletRe = /^[ \t]*[-*]\s+(.+)/gm;
  let bm: RegExpExecArray | null;
  while ((bm = bulletRe.exec(afterHeader)) !== null) {
    const text = bm[1].replace(/;$/, '').trim();
    if (text) criteria.push(text);
  }

  return criteria;
}
